### PR TITLE
Make react a dev/peer dependency and allow v0.15

### PR DESCRIPTION
**Pull request by chrisdevereux**

### CODE REVIEW

**Comment by kennethjiang** [comment]
Good point that `React` is just a peer dependency here!

2 questions:
- `React` is not a devDependency either, correct?
- I think we should remove `var React = require('react');` from the code. Not sure why I added it there to begin with. If we left that line there, then `react` is still a dependency not peerDependency.

**Comment by chrisdevereux** [comment]
Looking at the code, it looks like React shouldn't be a dependency of any kind -- the function should work regardless of whether you're using React, Angular or vanilla js. So maybe it would be better to just remove React from the dependencies (and the line you mention) altogether.

It's important to fix it somehow though. If the app's React version conflicts with this library's version then npm downloads a private copy of react for this lib and then two different copies of React end up getting pulled into the js bundle by webpack.

**Comment by kennethjiang** [comment]
Agreed @chrisdevereux The fewer dependencies we have the better. :) Do you want to revise your PR to reflect that?

**Comment by nealoke** [comment]
#10 Just posted this, didn't see this pull request. So +1 for this!

**Comment by nealoke** [comment]
@kennethjiang did you push this to npm already? :)

If I download it via npm i still get version `0.3.2` which is the same as before this merge. Please do so :)

**Comment by kennethjiang** [comment]
My apology I forgot to push! Just did. Please upgrade to version 0.3.3.

**Comment by nealoke** [comment]
@kennethjiang no worries ;) thanks!

**Pull request merged**
